### ISSUE TITLE
how to predict

### ISSUE THREAD

**Issue by shaomai00** [mmehdig/seq2seq-attention-model#2]
when i want to predict, I found that it's impossible to input the test_trgs because it doesn't exist actually ... so how should I predict a sample?

**Comment by mmehdig** [comment]
Hello @shaomai00, thank you for your interest in this short project. The textual corpus was the contribution of someone else in my experiment with Keras. I can ask and see if I can put it in my github repository. But as a short explanation: this text is a generated text, built based on a simple syntactic rules. These rules produce two languages which have different tree structures at the end so the translation would be about learning how to translate underlying trees.

**Comment by shaomai00** [comment]
ok,thank you. And my new question is I found the encoder_decoder model's input needs [src_input, trg_input] ,after I fit a model, I realized that if I want to predict, I must feed the trg_input which doesn't exsit (when I predict a sentence,I only have src...). So how could that be possible? should I change the model's structure?

**Comment by mmehdig** [comment]
Aha, ok! So the solution is that you start from an empty target sentence with just start marker `<s>` in the sentence. Then for total prediction, you predict a word on each time step until you reach the end of sentence.

**Comment by shaomai00** [comment]
I got it! thank you for your explanation~
